export const GENDER_OPTIONS = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
] as const

export type GenderValue = (typeof GENDER_OPTIONS)[number]['value']

export const REGISTER_COPY = {
  eyebrow: 'New Membership',
  heroHeadline: 'Become a',
  heroAccent: 'Member',
  heroDescription:
    'Join Roar Fitness and unlock expert coaching, premium equipment, and a community built for results.',
  benefit1: 'Expert coaching',
  benefit2: '24/7 studio access',
  benefit3: 'Flexible plans',
  stepPersonal: 'Personal',
  stepContact: 'Contact',
  stepSecurity: 'Security',
  sectionPersonalTitle: 'About you',
  sectionPersonalDescription: 'Your basic profile information.',
  sectionContactTitle: 'How can we reach you?',
  sectionContactDescription: 'We will use these details for your account and updates.',
  sectionSecurityTitle: 'Secure your account',
  sectionSecurityDescription: 'Choose a strong password to protect your membership.',
  formTitle: 'Create your account',
  formDescription: 'Complete all sections below to get started.',
  firstNameLabel: 'First name',
  firstNamePlaceholder: 'John',
  lastNameLabel: 'Last name',
  lastNamePlaceholder: 'Doe',
  dateOfBirthLabel: 'Date of birth',
  nicNumberPlaceholder: 'National Identity Card number',
  genderLabel: 'Gender',
  genderPlaceholder: 'Select gender',
  emailLabel: 'Email address',
  emailPlaceholder: 'you@email.com',
  phoneLabel: 'Phone number',
  phonePlaceholder: '+94 77 123 4567',
  addressLabel: 'Address',
  addressPlaceholder: 'Street address, city',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Create a password',
  confirmPasswordLabel: 'Confirm password',
  confirmPasswordPlaceholder: 'Re-enter your password',
  submitLabel: 'Continue to payment',
  submittingLabel: 'Saving details…',
  successMessage: 'Account created — welcome to Roar Fitness. Redirecting…',
  hasAccount: 'Already have an account?',
  signIn: 'Sign In',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  backHome: 'Back to home',
} as const
